name: example
description: A new Flutter project.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  # For Dio Kit
  dio: ^5.0.0

dependency_overrides:
  friflex_dev_plugins:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.22.0
  friflex_dev_plugins:
    path: ../
  friflex_dev_plugins_ui:
    path: ../kits/friflex_dev_plugins_ui
  friflex_dev_plugins_perf:
    path: ../kits/friflex_dev_plugins_perf
  friflex_dev_plugins_console:
    path: ../kits/friflex_dev_plugins_console
  friflex_dev_plugins_dio:
    path: ../kits/friflex_dev_plugins_dio
  friflex_dev_plugins_channel_monitor:
    path: ../kits/friflex_dev_plugins_channel_monitor

flutter:
  uses-material-design: true
