name: friflex_dev_plugins
description: UME is an in-app debug kits platform for Flutter apps. Produced by Flutter Infra team of ByteDance.
version: 1.0.0
homepage: https://github.com/mozerrr/friflex_dev_plugins

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
  flutter_lints: ^2.0.2

flutter:
