name: friflex_dev_plugins_channel_monitor
description: channel monitor kit for friflex_dev_plugins
version: 1.0.0
homepage: https://github.com/bytedance/friflex_dev_plugins

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  friflex_dev_plugins: ^1.0.0
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
