name: friflex_dev_plugins_console
description: Show debugPrint kit for friflex_dev_plugins.
version: 1.0.0-beta
homepage: https://github.com/bytedance/friflex_dev_plugins

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.0.0
  shared_preferences: ^2.0.18
  friflex_dev_plugins: '>1.0.0-beta <1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
