name: friflex_dev_plugins_ui
description: UI Kits for friflex_dev_plugins.
version: 1.0.0
homepage: https://github.com/bytedance/friflex_dev_plugins

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  friflex_dev_plugins: ^1.0.0
  cyclop: ^0.6.2
  quiver: ^3.2.1
  basics: ">=0.6.0 <0.11.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
