name: coverage

on:
  push:
    branches:
      - master
    paths:
      - "lib/**"
      - "kits/friflex_dev_plugins_console/lib/**"
      - "kits/friflex_dev_plugins_perf/lib/**"
      - "kits/friflex_dev_plugins_ui/lib/**"
      - "kits/friflex_dev_plugins_dio/lib/**"
    tags:
      - "coverage-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge
        working-directory: kits/friflex_dev_plugins_perf
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge
        working-directory: kits/friflex_dev_plugins_ui
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge
        working-directory: kits/friflex_dev_plugins_console
      - run: |
          flutter pub get
          flutter pub run flutter_coverage_badge
        working-directory: kits/friflex_dev_plugins_dio
      - name: Commit badges
        run: |
          git config --global user.name mozerrr
          git config --global user.email mozerrr@users.noreply.github.com
          git add coverage_badge.svg kits/friflex_dev_plugins_perf/coverage_badge.svg kits/friflex_dev_plugins_ui/coverage_badge.svg kits/friflex_dev_plugins_console/coverage_badge.svg kits/friflex_dev_plugins_dio/coverage_badge.svg
          git commit -m "Automated report coverage"
          git push
