name: Flutter Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_all_kits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - uses: subosito/flutter-action@v2.7.1
        with:
          channel: "stable"
      - name: Run test for UME
        run: flutter test --enable-vmservice
      - name: Run test for UME Device kit
        run: flutter test --enable-vmservice
        working-directory: kits/friflex_dev_plugins_device
      - name: Run test for UME Perf kit
        run: flutter test --enable-vmservice
        working-directory: kits/friflex_dev_plugins_perf
      - name: Run test for UME Show code kit
        run: flutter test --enable-vmservice
        working-directory: kits/friflex_dev_plugins_show_code
      - name: Run test for UME UI kit
        run: flutter test --enable-vmservice
        working-directory: kits/friflex_dev_plugins_ui
      - name: Run test for UME Console kit
        run: flutter test --enable-vmservice
        working-directory: kits/friflex_dev_plugins_console
      - name: Run test for UME Dio kit
        run: flutter test --enable-vmservice
        working-directory: kits/friflex_dev_plugins_dio
